### ISSUE TITLE
Small Board should support multiple hunts

### ISSUE THREAD

**Issue by erwa** [cardinalitypuzzles/smallboard#156]
A nice-to-have for the future is for Small Board to support multiple hunts. Currently, we need to wipe the database before each hunt.

In order to support multiple hunts, most of our database queries need to be made hunt-specific. Right now, some of our queries are hunt-specific (they specify hunt_pk) while others are not, which can lead to issues like the following:
```
Internal Server Error: /hunts/1/puzzles
Traceback (most recent call last):
  File "/mnt/c/Users/volde/Desktop/github/cardinalitypuzzles/smallboard/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/mnt/c/Users/volde/Desktop/github/cardinalitypuzzles/smallboard/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/mnt/c/Users/volde/Desktop/github/cardinalitypuzzles/smallboard/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/volde/Desktop/github/cardinalitypuzzles/smallboard/venv/lib/python3.7/site-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/mnt/c/Users/volde/Desktop/github/cardinalitypuzzles/smallboard/venv/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/mnt/c/Users/volde/Desktop/github/cardinalitypuzzles/smallboard/hunts/views.py", line 91, in puzzles
    sorted_np_pairs = PuzzleTree(puzzle_objects).get_sorted_node_parent_pairs()
  File "/mnt/c/Users/volde/Desktop/github/cardinalitypuzzles/smallboard/puzzles/puzzle_tree.py", line 77, in __init__
    node.parents = [self.puzzle_to_node[meta.pk] for meta in p.metas.all()]
  File "/mnt/c/Users/volde/Desktop/github/cardinalitypuzzles/smallboard/puzzles/puzzle_tree.py", line 77, in <listcomp>
    node.parents = [self.puzzle_to_node[meta.pk] for meta in p.metas.all()]
KeyError: 299
```

**Comment by rgossiaux** [comment]
Do you know what's required for this? I started poking around locally (without any integrations) and so far haven't hit any issues. I imagine some work might need to be done for thinking about how the integrations should work, but I didn't hit the stack trace from the report for example.

**Comment by rawxfish** [comment]
One buggy behavior is that it's not possible to have two puzzles with same name but belonging to different hunts. I think we just weren't careful with some of the uniqueness checks, but it shouldn't be that hard to fix in theory.

**Comment by akirabaruah** [comment]
> One buggy behavior is that it's not possible to have two puzzles with same name but belonging to different hunts. I think we just weren't careful with some of the uniqueness checks, but it shouldn't be that hard to fix in theory.

+1 maybe it'd be sufficient to replace the `Puzzle.name` field's `unique=True` with `Puzzle.Meta.constraints = UniqueConstraint(fields=('name', 'hunt'))` for the overall Puzzle model?

**Comment by akirabaruah** [comment]
Another thought: should we make the `Puzzle.url` field required and enforce uniqueness on that field instead of the name?

**Comment by rawxfish** [comment]
> +1 maybe it'd be sufficient to replace the Puzzle.name field's unique=True with Puzzle.Meta.constraints = UniqueConstraint(fields=('name', 'hunt')) for the overall Puzzle model?

We probably need to do a quick sweep of all the models to make sure they're all doing stuff that make sense with multiple hunts.

> Another thought: should we make the Puzzle.url field required and enforce uniqueness on that field instead of the name?
 
I feel like we had a discussion about this last year and decided on name because it wasn't clear how to canonize urls maybe? I might be making this up.

For sheets integration, smallboard globally is linked with a single folder and template sheet that it replicates, so we'd have a drive folder with sheets from multiple hunts...which is sorta unpleasant if we ever wanted to browse the drive. We shoudl change it to make a folder per hunt automatically or something.

**Comment by rgossiaux** [comment]
Ah yeah, puzzle urls and names are assumed to be globally unique right now. Yeah, they both only need to be unique per-hunt, right? And some of the tagging-related logic looks a little sketchy too since tags could be reused across hunts (I think?). 

Maybe one ideal state could be something like: support arbitrary numbers of concurrent hunts; use folders in google drive and messaging services (discord/slack) to separate data for different hunts; have per-hunt auth for smallboard and the various folders. Then we could run a permanent instance across multiple puzzle hunts and also have multiple teams using it for the same hunt. Maybe that's not actually that valuable though.

**Comment by akirabaruah** [comment]
> We probably need to do a quick sweep of all the models to make sure they're all doing stuff that make sense with multiple hunts.

I guess we could just look at any models that are related to `Hunt`?

> I feel like we had a discussion about this last year and decided on name because it wasn't clear how to canonize urls maybe? I might be making this up.

👍  Looks like we discussed it in https://github.com/cardinalitypuzzles/smallboard/issues/67 - was that the discussion you were thinking about? I'm probably missing something, but how might canonicalization of URLs hinder URL uniqueness? If anything, it seems like it would introduce duplication issues rather than collisions, in which case enforcing unique URLs might be okay?

Based on https://github.com/cardinalitypuzzles/smallboard/pull/104, it looks like we replaced `unique=True` with `blank=True` since we can't have `blank=True` *and* `unique=True` simultaneously for a CharField or URLField. But we can get around this by also specifying `null=True` as [recommended here](https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.Field.null).

> Ah yeah, puzzle urls and names are assumed to be globally unique right now. Yeah, they both only need to be unique per-hunt, right? And some of the tagging-related logic looks a little sketchy too since tags could be reused across hunts (I think?).

It looks like we [currently enforce](https://github.com/cardinalitypuzzles/smallboard/blob/cba90c7c6fc8490727895695b9083ec26fa87a2e/puzzles/models.py#L32) uniqueness for names (but not URLs). Aren't URLs globally unique by construction? e.g. even if two hunts each have a puzzle with the same name, those puzzles would have different URLs, right?

> Maybe one ideal state could be something like: support arbitrary numbers of concurrent hunts; use folders in google drive and messaging services (discord/slack) to separate data for different hunts; have per-hunt auth for smallboard and the various folders. Then we could run a permanent instance across multiple puzzle hunts and also have multiple teams using it for the same hunt. Maybe that's not actually that valuable though.

👍  agreed - I also was recently thinking that multi-hunt and multi-team support with a single public instance would be awesome (probably prioritized in that order). Would be great to use the same tech stack for Teddy Set Go teams without reinventing the wheel 😄

**Comment by rgossiaux** [comment]
> > Ah yeah, puzzle urls and names are assumed to be globally unique right now. Yeah, they both only need to be unique per-hunt, right? And some of the tagging-related logic looks a little sketchy too since tags could be reused across hunts (I think?).
> 
> It looks like we [currently enforce](https://github.com/cardinalitypuzzles/smallboard/blob/cba90c7c6fc8490727895695b9083ec26fa87a2e/puzzles/models.py#L32) uniqueness for names (but not URLs). Aren't URLs globally unique by construction? e.g. even if two hunts each have a puzzle with the same name, those puzzles would have different URLs, right?

It's not a DB constraint but it still seems to be assumed in the application: https://github.com/cardinalitypuzzles/smallboard/blob/cba90c7c6fc8490727895695b9083ec26fa87a2e/puzzles/models.py#L85

Not sure why though, maybe that check should just be dropped. It's definitely conceivable to me that two puzzles in the same hunt could share a URL.

**Comment by akirabaruah** [comment]
> Not sure why though, maybe that check should just be dropped. It's definitely conceivable to me that two puzzles in the same hunt could share a URL.

+1 yeah maybe it's just an assumption that we can remove if we enforce combined (hunt, name) uniqueness?

Yeah, especially for simpler hunts that might use a single PDF or webpage (although for that particular example, we could use `<PDF URL>#page=[page number]` or something).

**Comment by erwa** [comment]
I agree with @rgossiaux's suggestion in https://github.com/cardinalitypuzzles/smallboard/issues/191#issuecomment-732520880 that it's probably easiest just to have each hunt instance be a team's own view of a hunt, and each hunt instance is completely sandboxed from other hunt instances. 

I was thinking we could have an "Add Hunt" button, and when adding a hunt, you would configure:
* hunt name
* team name
* Google Drive folder
* Discord server
* [optional] list of users who are allowed access to this hunt instance

The default hunts/ page could list all the hunt instances, which might look like:
* Hunt X - Team A
* Hunt X - Team B
* Hunt Y - Team A
* ...

One might argue that you should group all instances of a particular hunt together, but I don't think it adds much value, since teams will be isolated from one another (completely separate puzzle instances and answer submissions).

**Comment by rgossiaux** [comment]
We could have it create the Drive folder/sheet automatically instead of asking people to provide one, too. That would be pretty helpful I think.

I've been thinking about what it would take for us to actually want to use smallboard for multiple hunts since some of this is kind of moot if we're only ever going to use it once a year for mystery hunt (we could still run a public instance for many mystery hunt teams to use concurrently but it's possible teams wouldn't be comfortable entrusting their data with us). Most smaller hunts I think everyone can hold essentially the state of the entire hunt in their head at once, so the friction from using smallboard might not be worth it. Puzzle Boat might be a good next testing ground since it's the next biggest hunt.

Some scattered thoughts on utility for other hunts:

* Some amount of scraping / automatic puzzle import could be a killer feature. It's nontrivial but I think it could be done, possibly with some quick manual config/assistance at the start of a new hunt to help the scraper. The main friction from using smallboard is probably in adding new puzzles and updating solved puzzles with answers, so if it could mostly do that automatically I think that would help a lot.

* The existing tracking answers for meta spreadsheets is already very useful. This would have been handy for us in the last Puzzle Boat, for example.

* Handling discord channels would be a bit useful. In the manual world I like having multiple existing voice channels and then reusing & renaming them for new puzzles. If smallboard could quickly create new voice channels for new puzzles, and clean up the old ones soon enough to not totally pollute the server, that would be a time saver.

* Handling the sheet permissions automatically (making sure everyone is added so that their names appear in the sheets, for example) is useful.

I think that's about all I can think of for benefits to a small hunt (O(20) puzzles and O(6) people say)

**Comment by akirabaruah** [comment]
> We could have it create the Drive folder/sheet automatically instead of asking people to provide one, too. That would be pretty helpful I think.
> 
> I've been thinking about what it would take for us to actually want to use smallboard for multiple hunts since some of this is kind of moot if we're only ever going to use it once a year for mystery hunt (we could still run a public instance for many mystery hunt teams to use concurrently but it's possible teams wouldn't be comfortable entrusting their data with us). Most smaller hunts I think everyone can hold essentially the state of the entire hunt in their head at once, so the friction from using smallboard might not be worth it. Puzzle Boat might be a good next testing ground since it's the next biggest hunt.

I agree that smallboard seems generally useful for larger hunts. That being said, I think we should try to make this platform as robust as possible, while prioritizing more critical features for the upcoming MITMH for Cardinality.

Re: user trust, do you mean trusting us with their puzzle solve data? I wonder if we can include a section in the privacy/ToS page that says that we don't intend to use any data on this site, but cannot guarantee any protection (for now)? Personally, I'd use a platform if it makes my puzzle hunting experience better, even if there's a small risk that folks might steal my answers.

> 
> Some scattered thoughts on utility for other hunts:
> 
> * Some amount of scraping / automatic puzzle import could be a killer feature. It's nontrivial but I think it could be done, possibly with some quick manual config/assistance at the start of a new hunt to help the scraper. The main friction from using smallboard is probably in adding new puzzles and updating solved puzzles with answers, so if it could mostly do that automatically I think that would help a lot.

I was actually tinkering with `scrapy` and got a scraper proof-of-concept to crawl teammatehunt.com and successfully grab all the puzzles (as far as I can tell manually). I can upload a PR if folks are interested :+1: My motivation was to create a historical collection of as many puzzles as possible for training, etc. - not sure if that's a goal for smallboard, but happy to share the code anyway :smile: just lemme know

> * The existing tracking answers for meta spreadsheets is already very useful. This would have been handy for us in the last Puzzle Boat, for example.
> * Handling discord channels would be a bit useful. In the manual world I like having multiple existing voice channels and then reusing & renaming them for new puzzles. If smallboard could quickly create new voice channels for new puzzles, and clean up the old ones soon enough to not totally pollute the server, that would be a time saver.
> * Handling the sheet permissions automatically (making sure everyone is added so that their names appear in the sheets, for example) is useful.
>
> I think that's about all I can think of for benefits to a small hunt (O(20) puzzles and O(6) people say)

+1 to all of these. Thanks for the analysis!

**Comment by rgossiaux** [comment]
Ok I think #261 (using separate tags per hunt) is the last change to the smallboard models themselves needed to support multiple hunts AFAIK. The integrations still need changes and we'd have to add a better permissions model but at least we won't need to clear the db after mystery hunt this year, I think.

**Comment by erwa** [comment]
This is done, I think?

**Comment by rawxfish** [comment]
Wait this is not done I think. For example, there is no way to set per hunt users. We are still making a new small board for each hunt =/

**Comment by erwa** [comment]
Oh, I was gonna file a separate issue for that. I took this issue to mean the ability to create multiple hunts on one smallboard instance, which is currently possible. What you're talking about I consider more multi-tenancy: having different teams be able to use the same smallboard instance for the same and or different hunts (probably need to create a new hunt instance per team per hunt).

Anyways, I'll leave this issue open for now and file a separate issue for setting per-hunt users that I'll link to this issue.

**Comment by rawxfish** [comment]
Ah okay, we can also close this if it's cleaner to split it into smaller / more specific issues.

**Comment by erwa** [comment]
Just created #501. Let's close this and shift future discussion to that and other issues.
