### ISSUE TITLE
Burn down chart visualization

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/smallboard#200]
@cs-miller brought up the valuable feature of visualizing a team's Hunt progress as a [burn down chart](https://en.wikipedia.org/wiki/Burn_down_chart). This visualization can help keep moral high as we make progress on a hunt.

It can also serve as visual metric of our average team solve rate as the hunt progresses.

**Comment by bcai2** [comment]
Would a "build-up"-type chart be more feasible? It would be hard to set a starting point for a burn-down chart if we don't know exactly how many puzzles the hunt's going to contain or that we'll encounter.

(Otherwise, we can just make an adjustable estimate initially set to 200 or so.)

I'm thinking something along the lines of http://www.mit.edu/~puzzle/2020/statistics/, with visible meta solves as well.

**Comment by bcai2** [comment]
Outline of what I'm thinking for this:

- [x] Timestamps (#219, sort of) 
- [ ] Basic stats page
  - [ ] Total puzzles completed
  - [ ] Total puzzles unsolved
  - [ ] Total puzzles open
  - [ ] Integrate this with the applet
- [ ] Progress bar line graph
  - [ ] Make graph
  - [ ] Integrate with stats page

**Comment by bcai2** [comment]
The page has been implemented! (#378)
Marking this as resolved and merging the updating into the update issue (#390).
