### ISSUE TITLE
Remove PENDING Puzzle status

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/smallboard#217]
Since we don't phone in answers anymore, we'll likely never be waiting a long time to verify Answers for Puzzles.

**Comment by ramansrivastava** [comment]
@asdfryan thnks for recommending me this issue can i get assigned ,and can you tell me a bit more about this issue?

**Comment by akirabaruah** [comment]
Welcome to the project @ramansrivastava!

Each Puzzle can have a status of various types, including PENDING, listed here:
https://github.com/cardinalitypuzzles/smallboard/blob/3e49bace2dfd13b2780f47cb1670293bb6574402/puzzles/models.py#L47

We'd like to remove that PENDING type, along with any code associated with it.

**Comment by ramansrivastava** [comment]
@akirabaruah so you want me to remove PENDING from every line of code right

**Comment by akirabaruah** [comment]
Yes, essentially 👍 but you'll also want to [run tests](https://github.com/cardinalitypuzzles/smallboard/blob/master/dev-guide.md#running-tests) to ensure that everything is still working after that

**Comment by ramansrivastava** [comment]
ok i can do that

**Comment by akirabaruah** [comment]
There might also be some logic that transitions Puzzles through the states like SOLVING -> PENDING -> SOLVED. We'll have to make sure that any logic like that instead goes from SOLVING -> SOLVED instead, I think. In any case, to start, I'd recommend trying to remove all instances of PENDING and we can go from there.

Thanks for working on this!

**Comment by akirabaruah** [comment]
Also @ramansrivastava - just curious, how'd you find our project? 😄

**Comment by ramansrivastava** [comment]
got it, will text if i get stuck.

**Comment by ramansrivastava** [comment]
@akirabaruah i was just going through topics and needed something to work on.

**Comment by rgossiaux** [comment]
Actually just catching up here, do we actually need to remove the PENDING state or can we just change the add answer logic to skip over it directly to SOLVED conditional on some setting? Personally I'd rather keep the functionality around because I think there are very real odds that phoning in answers comes back in one of the next mystery hunts.

**Comment by asdfryan** [comment]
> Actually just catching up here, do we actually need to remove the PENDING state or can we just change the add answer logic to skip over it directly to SOLVED conditional on some setting? Personally I'd rather keep the functionality around because I think there are very real odds that phoning in answers comes back in one of the next mystery hunts.

This also applies to the whole AnswerQueue feature. If we want to keep it around, it'd have to be a per-hunt setting right? (since basically all other hunts do not have a phone-in answer system). 

Personally, I think that the probability of the return of phone-in answers is rather low, and I'm OK with sunsetting this feature or just marking it as deprecated with a comment. 

If it *does* come back, I imagine that Mystery Hunt organizers will give ample warning for scenarios like this (or we can contact them to ask).

**Comment by ramansrivastava** [comment]
so should i start working on this?

**Comment by rgossiaux** [comment]
> > Actually just catching up here, do we actually need to remove the PENDING state or can we just change the add answer logic to skip over it directly to SOLVED conditional on some setting? Personally I'd rather keep the functionality around because I think there are very real odds that phoning in answers comes back in one of the next mystery hunts.
> 
> This also applies to the whole AnswerQueue feature. If we want to keep it around, it'd have to be a per-hunt setting right? (since basically all other hunts do not have a phone-in answer system).
> 
> Personally, I think that the probability of the return of phone-in answers is rather low, and I'm OK with sunsetting this feature or just marking it as deprecated with a comment.
> 
> If it _does_ come back, I imagine that Mystery Hunt organizers will give ample warning for scenarios like this (or we can contact them to ask).

Right, I was thinking of a per-hunt setting of some kind. I think it is mostly just a question of taste or personality; I think you are more aggressive about deleting features and I am more conservative about it. It's not a hill I want to die on and I don't think we should be spending much time on the feature but my vote is that given that we already have it and have it working, leaving it around isn't very harmful and I think it may be useful. 

Last year was the first year without calling in answers, after all, and it was before that a very long-standing mystery hunt tradition, and I think some writing teams felt that it added a more personal touch to the hunt and gave HQ a way to check in with people and so on, so that's why I'm not convinced it's guaranteed to be gone for good. Since it's a new set of people in charge each year I can easily see a writing team going back on this again.

But that's just my opinion and if the group feels differently I'm fine with that too.

**Comment by akirabaruah** [comment]
@ramansrivastava for now, let's hold off on deleting `PENDING` until we come to a decision about whether to remove it. If you'd like to work on some other Python changes, we can use some more test coverage in the `hunts/` app. Are you familiar with writing django tests?

**Comment by ramansrivastava** [comment]
> @ramansrivastava for now, let's hold off on deleting `PENDING` until we come to a decision about whether to remove it. If you'd like to work on some other Python changes, we can use some more test coverage in the `hunts/` app. Are you familiar with writing django tests?

i know python ,but never worked with django but i think i can do that.

**Comment by akirabaruah** [comment]
I agree with @rgossiaux's point that it doesn't hurt to keep this feature and there's a chance that it can be useful for future MITMHs. At the same time, I share @asdfryan's bias towards removing things for the sake of keeping our feature set concise.

Is there any large risk in removing this status from Puzzle (along with AnswerQueue) and potentially reverting the commit(s) in the future if we need to bring them back? If not, I'd lean towards removing in this case.

**Comment by akirabaruah** [comment]
> > @ramansrivastava for now, let's hold off on deleting `PENDING` until we come to a decision about whether to remove it. If you'd like to work on some other Python changes, we can use some more test coverage in the `hunts/` app. Are you familiar with writing django tests?
> 
> i know python ,but never worked with django but i think i can do that.

Okay, great! If you can get your local setup to a point where you can run the existing tests, then I think you should be able to add some new tests in the `hunts/` directory. Let's continue the discussion in #239

**Comment by asdfryan** [comment]
Update: We will make an environment variable to disable/enable the feature (default to disable), along with the answer queue page.
