### ISSUE TITLE
Clickable Puzzle tags

### ISSUE THREAD

**Issue by akirabaruah** [cardinalitypuzzles/smallboard#218]
Puzzles have tags. Users should be able to click on tags in the UI to filter the Puzzle list to include Puzzles with the selected tag only.

**Comment by rgossiaux** [comment]
Should wait for the react rewrite (#251 ) before adding this

**Comment by rgossiaux** [comment]
This is unblocked now.

To do this, I think we will want to use the `useFilters` hook on react-table to add a column filter for the tags column.

Unfortunately I think the default behavior for this is likely the same bad behavior there was for global filters: a subrow only appears if all of its ancestors match the filter (because internally react-table treats subrows as a top-down tree traversal, and any node that doesn't match gets pruned, which prunes all its descendants). 

To fix this we will probably need to patch useFilters.js in react-table like we patched useGlobalFilters.js. You can look at the existing patch file to see what that looked like (for filters it was a relatively small change though the logic isn't totally obvious). 

In order to generate the patch, you will need to:

* Navigate to the react-table directory in your node_modules
* Install the dependencies (`yarn install`) of react-table locally.
* Make your changes to the useFilters.js file
* Run `yarn run build` to rebuild the react-table.js output file with your changes
* Remove the new files you added from `yarn install` (I think `react-table/yarn.lock` as well as the `react-table/node_modules` subdirectory) so they don't get included in the patch.
* Go back to the smallboard root and run `yarn patch-package react-table` which should generate a new patchfile for the react-table library.
* Inspect the patch and make sure nothing crazy happened, and if it looks good, commit it!

Those steps are from memory so I may have missed something but I believe that's approximately the workflow.

Besides patching react-table, I think you can follow https://react-table.tanstack.com/docs/api/useFilters to see how to add a filter (there is example source linked there which should be helpful).

It might be easiest to use redux to keep track of the filter state, you can figure it out when implementing.

This is related to #220 in that I think that one is essentially a different column filter (filtering on the answers column instead). In particular I think they both have a dependency on the react-table patch changes mentioned here, and beyond that the implementations will probably look somewhat similar (though this one has a more complicated UI).

**Comment by rgossiaux** [comment]
@dan-simon if you're still interested in this issue feel free to grab the assignment. I'm not sure I did a good job conveying the scope on Discord so if you think you won't have time that's okay too.

**Comment by rgossiaux** [comment]
Merged in #404
