### ISSUE TITLE
Make puzzle creation fast

### ISSUE THREAD

**Issue by asdfryan** [cardinalitypuzzles/smallboard#250]
Bottleneck is currently in sheet creation. We should try creating the sheet asynchronously (and have a manual workaround to set the sheet if it fails).

**Comment by rgossiaux** [comment]
We might want to set up something like Celery. Then we can use it for various async tasks: Google API calls, Discord API calls, periodically running jobs (like cleaning up Discord channels).

I also really like @rawxfish 's idea of keeping around a few empty sheets that we can rename, instead of having to wait to copy a sheet before assigning it to a puzzle.
