### ISSUE TITLE
webpack not found when running docker-compose up in fresh checkout

### ISSUE THREAD

**Issue by erwa** [cardinalitypuzzles/smallboard#313]
In a fresh checkout of smallboard, after install prereqs like Docker and doing `cp .env.test .env`, if you run `docker-compose up`, there'll be an error in the `web` container log

```
web_1  | yarn run v1.22.4
web_1  | $ webpack --config webpack.dev.js ./hunts/src/index.js --output-path ./hunts/static
web_1  | /bin/sh: webpack: not found
web_1  | error Command failed with exit code 127.
```

If you open Small Board in a browser and try to open a hunt, it'll error out because `main.js` won't be found:
```
web_1  | [07/Jan/2021 22:40:53] "GET /static/main.js HTTP/1.1" 404 1647
```

Looking inside the container, it seems the entire `node_modules` folder is missing.

Manually running `yarn install` inside the container creates the `node_modules` folder and then restarting the container fixes the issue, but ideally the `Dockerfile` that creates the `web` container's image would be updated.

I encountered this while running Small Board in WSL2 on Windows.

**Comment by rgossiaux** [comment]
I think @bcai2 was having the same issue. The details are helpful. The Dockerfile does run yarn install (https://github.com/cardinalitypuzzles/smallboard/blob/2a84bf00bf8673c95f7306711e8ec8ef43dce967/Dockerfile#L26) and I haven't been able to repro this myself but it clearly seems to be a problem. 

Going to see if I can repro this on a fresh checkout on OS X (both of you are on Windows but I only have mac & linux machines handy).

**Comment by rgossiaux** [comment]
Ok yeah, I can repro. I think the config is kind of fucked tbh, not really sure how this ever worked to begin with. The volume in `docker-compose.yaml` is bypassing the /usr/src/smallboard directory that's already in the image, so even though the image from the Dockerfile has `node_modules` installed correctly it doesn't matter. It only worked for me because I also had node_modules locally for some reason or another, probably when I was setting this up initially.
